pipeline {
    agent any

    tools {
        nodejs "NodeJS 18"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/devkelzs/jenkins-projects.git'
            }
        }
        stage('Install') {
            steps {
                dir('jenkins-ci-cd-project4') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('jenkins-ci-cd-project4') {
                    sh 'npm test'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('jenkins-ci-cd-project4') {
                    sh 'pm2 delete server || true'
                    sh 'pm2 start server.js --name node-ci-app'
                }
            }
        }
    }
}
