pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'kellynkwain/flaskapp:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone only the main branch
                git branch: 'main', url: 'https://github.com/devkelzs/jenkins-projects.git'
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-ci-cd-project5') {
                    sh 'pip3 install -r requirements.txt'
                    sh 'pytest tests/'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('jenkins-ci-cd-project5') {
                    sh 'docker build -t flaskapp:latest .'
                    sh 'docker tag flaskapp:latest $DOCKER_IMAGE'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    dir('jenkins-ci-cd-project5') {
                        sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                        sh 'docker push $DOCKER_IMAGE'
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('jenkins-ci-cd-project5') {
                    sh 'kubectl apply -f k8s-deployment.yaml'
                }
            }
        }
    }
}
