pipeline {
    agent any

    tools {
        maven 'Maven 3.8.8'
        jdk 'JDK 17'
    }

    environment {
        SONARQUBE_URL = 'http://34.227.87.230:9000'
        DOCKER_IMAGE = "kellynkwain/java-app:${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/devkelzs/jenkins-projects'
            }
        }

        stage('Build') {
            steps {
                dir('jenkins-CI-CD-pipeline-project2') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Code Analysis') {
            steps {
                dir('jenkins-CI-CD-pipeline-project2') {
                    withSonarQubeEnv('My SonarQube Server') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('jenkins-CI-CD-pipeline-project2') {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                      echo "$PASS" | docker login -u "$USER" --password-stdin
                      docker push $DOCKER_IMAGE
                    '''
                }
            }
        }
    }
}
