pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'python3 jenkins-ci-pipeline-project1/hello.py'
            }
        }

        stage('Test') {
            steps {
                sh 'pytest jenkins-ci-pipeline-project1/test_hello.py'
            }
        }
    }

    post {
        success {
            echo '✅ Job succeeded!'
        }
        failure {
            echo '❌ Job failed.'
        }
    }
}
