pipeline {
    agent any

    environment {
        VENV_DIR = "venv"  // name of the virtual environment folder
    }

    stages {
        stage('Set Up Virtual Environment') {
            steps {
                sh '''
                    python3 -m venv $VENV_DIR
                    . $VENV_DIR/bin/activate
                    pip install --upgrade pip
                    pip install -r jenkins-ci-pipeline-project1/requirements.txt
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    . $VENV_DIR/bin/activate
                    python3 jenkins-ci-pipeline-project1/hello.py
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    . $VENV_DIR/bin/activate
                    pytest jenkins-ci-pipeline-project1/test_hello.py
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Job succeeded!'
        }
        failure {
            echo '❌ Job failed.'
        }
    }
}

