pipeline {
    agent any

    stages {
        stage('Set Up Virtual Environment') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r jenkins-ci-pipeline-project1/requirements.txt
                '''
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    . venv/bin/activate
                    flake8 jenkins-ci-pipeline-project1 --exit-zero
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    . venv/bin/activate
                    python3 jenkins-ci-pipeline-project1/hello.py
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest jenkins-ci-pipeline-project1/test_hello.py
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Job succeeded!'
        }
        failure {
            echo '❌ Job failed.'
        }
    }
}
