pipeline {
    agent any

    tools {
        jdk 'jdk-17'
        maven 'maven'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/devkelzs/jenkins-projects.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('jenkins-ci-cd-project6/demo') {     // 👈 navigate into the folder with pom.xml
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'jenkins-ci-cd-project6/demo/target/*.war', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Build and archiving completed successfully.'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
