pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'kellynkwain/nodejs-k8s-app:latest'
    }

    options {
        skipDefaultCheckout() // Skip default SCM checkout to avoid conflicts
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/devkelzs/jenkins-projects.git'
                sh 'ls -la jenkins-ci-cd-project3' // Debug: Verify directory contents
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .' // Revert to legacy builder
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                dir('jenkins-ci-cd-project3') {
                    withCredentials([file(credentialsId: 'kubeconfig-minikube', variable: 'KUBECONFIG')]) {
                        sh 'ls -la' // Debug: Confirm deployment.yaml is present
                        sh '''
                            kubectl --kubeconfig=$KUBECONFIG delete deployment nodejs-deployment --ignore-not-found=true
                            kubectl --kubeconfig=$KUBECONFIG apply -f deployment.yaml
                        '''
                    }
                }
            }
        }
    }
}
