pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'kellynkwain/nodejs-k8s-app:latest'
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build Image') {
            steps {
                dir('jenkins-ci-cd-project3') {
                    sh '''
                        docker buildx create --use
                        docker buildx build -t $DOCKER_IMAGE .
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Debug Workspace') {
            steps {
                dir('jenkins-ci-cd-project3') {
                    sh 'ls -l'
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-minikube', variable: 'KUBECONFIG')]) {
                    dir('jenkins-ci-cd-project3') {
                        sh '''
                            if [ ! -f deployment.yaml ]; then
                                echo "ERROR: deployment.yaml not found"
                                exit 1
                            fi
                            kubectl --kubeconfig=$KUBECONFIG delete deployment nodejs-deployment --namespace=default --ignore-not-found=true
                            kubectl --kubeconfig=$KUBECONFIG apply -f deployment.yaml
                        '''
                    }
                }
            }
        }
    }
}
