pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/devkelzs/jenkins-projects/edit/main/jenkins-ci-cd-project2.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mkdir -p /tmp/website && cp -r * /tmp/website/'
            }
        }
        stage('Deploy') {
            steps {
                sh 'sudo rm -rf /var/www/html/my-static/*'
                sh 'sudo cp -r /tmp/website/* /var/www/html/my-static/'
                sh 'sudo chown -R www-data:www-data /var/www/html/my-static'
                sh 'sudo chmod -R 755 /var/www/html/my-static'
            }
        }
    }
}
